export interface Product {
    id: number
    name: string
    price: number
    salePrice?: number
    image: string
    category: string
    rating: number
    reviewCount: number
    inStock: boolean
    color: string
    brand: string
    organic?: boolean
  }
  
  export const products: Product[] = [
    {
      id: 1,
      name: "Yellow Potatoes Whole Fresh, 5lb Bag",
      price: 1.99,
      salePrice: 0.5,
      image: "/placeholder.svg?height=200&width=200",
      category: "Fruits & Vegetables",
      rating: 4,
      reviewCount: 3,
      inStock: true,
      color: "Yellow",
      brand: "Fresh",
      organic: false,
    },
    {
      id: 2,
      name: "Large Bagged Oranges",
      price: 1.78,
      salePrice: 0.89,
      image: "/placeholder.svg?height=200&width=200",
      category: "Fruits & Vegetables",
      rating: 4,
      reviewCount: 3,
      inStock: true,
      color: "Orange",
      brand: "Fresh",
      organic: true,
    },
    {
      id: 3,
      name: "Strawberries - 1lb",
      price: 5.45,
      salePrice: 1.5,
      image: "/placeholder.svg?height=200&width=200",
      category: "Fruits & Vegetables",
      rating: 3,
      reviewCount: 5,
      inStock: true,
      color: "Red",
      brand: "Fresh",
      organic: false,
    },
    {
      id: 4,
      name: "Simple Kitchen PD Sliced Strawberries - 10lbs",
      price: 24.9,
      salePrice: 21.5,
      image: "/placeholder.svg?height=200&width=200",
      category: "Frozen Foods",
      rating: 4,
      reviewCount: 3,
      inStock: true,
      color: "Red",
      brand: "Simple Kitchen",
      organic: false,
    },
    {
      id: 5,
      name: "Peach - each",
      price: 1.75,
      salePrice: 0.75,
      image: "/placeholder.svg?height=200&width=200",
      category: "Fruits & Vegetables",
      rating: 5,
      reviewCount: 3,
      inStock: true,
      color: "Orange",
      brand: "Fresh",
      organic: false,
    },
    {
      id: 6,
      name: "Marketside Fresh Organic Bananas, Bunch",
      price: 1.99,
      salePrice: 0.89,
      image: "/placeholder.svg?height=200&width=200",
      category: "Fruits & Vegetables",
      rating: 4,
      reviewCount: 7,
      inStock: true,
      color: "Yellow",
      brand: "Marketside",
      organic: true,
    },
    {
      id: 7,
      name: "Large Garden Spinach & Herb Wrap Tortillas",
      price: 3.99,
      salePrice: 2.79,
      image: "/placeholder.svg?height=200&width=200",
      category: "Breads & Bakery",
      rating: 4,
      reviewCount: 3,
      inStock: true,
      color: "Green",
      brand: "Garden",
      organic: false,
    },
    {
      id: 8,
      name: "Halloween Harvest Caramel Apple Soft Caramels",
      price: 21.37,
      salePrice: 19.37,
      image: "/placeholder.svg?height=200&width=200",
      category: "Biscuits & Snacks",
      rating: 5,
      reviewCount: 3,
      inStock: true,
      color: "Brown",
      brand: "Halloween",
      organic: false,
    },
    {
      id: 9,
      name: "Fresh Purple Eggplant",
      price: 3.99,
      salePrice: 2.99,
      image: "/placeholder.svg?height=200&width=200",
      category: "Fruits & Vegetables",
      rating: 4,
      reviewCount: 5,
      inStock: true,
      color: "Purple",
      brand: "Fresh",
      organic: false,
    },
    {
      id: 10,
      name: "Fresh Pomegranate, Each",
      price: 2.99,
      salePrice: 1.5,
      image: "/placeholder.svg?height=200&width=200",
      category: "Fruits & Vegetables",
      rating: 5,
      reviewCount: 8,
      inStock: true,
      color: "Red",
      brand: "Fresh",
      organic: false,
    },
  ]
  
  